submission {
    author = "author1"
    id = "id1"
    score = 1
    title = "title1"
    subreddit = "subreddit"
    nsfw = true
    spoiler = true
}

submission {
    author = "author2"
    id = "id2"
    score = 2
    title = "title2"
    linkFlairText = "flair"
    subreddit = "subreddit"
    nsfw = false
    spoiler = false
}

submission {
    author = "author3"
    id = "id3"
    score = 3
    title = "title3"
    linkFlairText = "flair"
    subreddit = "subreddit"
    nsfw = true
    spoiler = true
}

submission {
    author = "author4"
    id = "id4"
    score = 4
    title = "title4"
    linkFlairText = "flair"
    subreddit = "subreddit"
    nsfw = true
    spoiler = false
}

submission {
     author = "author5"
     id = "id5"
     score = 5
     title = "title5"
     linkFlairText = "flair"
     subreddit = "subreddit"
     nsfw = false
     spoiler = true
 }